2019-06-13 10:38:34,195-logYeile.py|TypeError("unhashable type: 'list'",)
